# Generated by Django 3.1.2 on 2021-09-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bursalist',
            fields=[
                ('auto_increment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('company_official', models.CharField(max_length=100)),
                ('company_listing', models.CharField(max_length=100)),
                ('company_tickname', models.CharField(max_length=100)),
                ('company_status', models.CharField(max_length=100)),
            ],
        ),
    ]
