# Generated by Django 3.1.2 on 2021-09-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chatbot', '0002_bursalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursalist',
            name='exchange',
            field=models.CharField(default='bursa', max_length=100),
        ),
    ]
