# Generated by Django 3.1.2 on 2021-09-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chatbot', '0003_bursalist_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursalist',
            name='trading_view_symbol',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
