# Generated by Django 3.1.2 on 2021-09-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chatbot', '0006_option3_stock_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentimentanalysistop10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=200)),
                ('top10', models.CharField(max_length=300)),
            ],
        ),
    ]
