# Generated by Django 3.1.2 on 2021-09-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasa_chatbot', '0007_sentimentanalysistop10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentimentanalysistop10',
            name='top10',
            field=models.CharField(max_length=1000),
        ),
    ]
